"""
graphite/claim.py — Claim: the first-class trust primitive.

A Claim is the atomic unit of the Graphite trust engine. Every assertion
about a relationship, attribute, or risk goes through Claim first.
Edges in the graph are one way to *materialize* a Claim, but the Claim
itself carries the full evidence chain, confidence breakdown, and
dependency links.

Pipeline:
  Extractor → Claim[] → (optional) Edge materialization → Graph
"""
import hashlib
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field

from .enums import AssertionMode, ConfidenceLevel
from .schemas import Provenance


# ═══════════════════════════════════════
# Claim Enums
# ═══════════════════════════════════════

class ClaimType(str, Enum):
    """What kind of assertion this claim makes."""
    RELATIONSHIP = "RELATIONSHIP"       # "A supplies to B"
    ATTRIBUTE = "ATTRIBUTE"             # "A's revenue is $10B"
    RISK_ASSERTION = "RISK_ASSERTION"   # "A is exposed to China refining risk"
    DEPENDENCY = "DEPENDENCY"           # "A depends on B for sole-source component"


class ClaimStatus(str, Enum):
    """Trust verdict for a claim — typically computed, not manually set."""
    SUPPORTED = "SUPPORTED"             # Evidence meets threshold
    WEAK = "WEAK"                       # Some evidence but below threshold
    MIXED = "MIXED"                     # Supporting AND weakening evidence present
    UNSUPPORTED = "UNSUPPORTED"         # No or rejected evidence
    PENDING_REVIEW = "PENDING_REVIEW"   # Awaiting analyst decision


class ReviewState(str, Enum):
    """Analyst review workflow state."""
    UNREVIEWED = "UNREVIEWED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    NEEDS_FOLLOWUP = "NEEDS_FOLLOWUP"


class ClaimOrigin(str, Enum):
    """How this claim was created."""
    EXTRACTOR = "EXTRACTOR"             # Produced by an extraction pipeline
    AGENT = "AGENT"                     # Generated by an AI agent
    RULE_ENGINE = "RULE_ENGINE"         # Inferred by scoring rules
    ANALYST = "ANALYST"                 # Manually entered by a human
    IMPORTED = "IMPORTED"               # Bulk-imported from external system


class ClaimGranularity(str, Enum):
    """Abstraction level of a claim.

    ATOMIC: single extractable fact from a document.
    SYNTHESIZED: combined from multiple atomic claims.
    THESIS: high-level investment/risk thesis for UI display.
    """
    ATOMIC = "ATOMIC"
    SYNTHESIZED = "SYNTHESIZED"
    THESIS = "THESIS"


# ═══════════════════════════════════════
# Confidence (explainable)
# ═══════════════════════════════════════

class ConfidenceFactor(BaseModel):
    """One factor contributing to the overall confidence score.

    Example:
        ConfidenceFactor(
            name="source_count",
            raw_value="3 independent sources",
            contribution=0.15,
            direction="POSITIVE",
            explanation="3 independent sources confirm this claim",
        )
    """
    name: str = Field(description="Factor name: source_count, source_diversity, directness, recency, doc_quality, counter_penalty")
    raw_value: str = Field(description="Human-readable raw value, e.g. '3 sources', '2024-01-15'")
    contribution: float = Field(description="Normalized contribution to final score, e.g. +0.15 or -0.08")
    direction: str = Field(default="POSITIVE", description="POSITIVE or NEGATIVE")
    explanation: str = Field(description="Why this factor matters for this claim")


class ConfidenceResult(BaseModel):
    """Explainable confidence breakdown for a claim.

    The score is computed from factors, never manually assigned.
    The level (HIGH/MEDIUM/LOW) is derived from the score for
    backwards compatibility with existing ConfidenceLevel enum.
    """
    score: float = Field(ge=0.0, le=1.0, description="Computed confidence 0.0 - 1.0")
    level: ConfidenceLevel = Field(description="Derived from score: HIGH >= 0.7, MEDIUM >= 0.4, LOW < 0.4")
    factors: List[ConfidenceFactor] = Field(default_factory=list, description="Explainable breakdown")

    @classmethod
    def from_score(cls, score: float, factors: List[ConfidenceFactor] = None) -> "ConfidenceResult":
        """Create a ConfidenceResult from a raw score, deriving the level."""
        score = max(0.0, min(1.0, score))
        if score >= 0.7:
            level = ConfidenceLevel.HIGH
        elif score >= 0.4:
            level = ConfidenceLevel.MEDIUM
        else:
            level = ConfidenceLevel.LOW
        return cls(score=round(score, 4), level=level, factors=factors or [])


# ═══════════════════════════════════════
# Claim (the core primitive)
# ═══════════════════════════════════════

def _make_claim_id(
    subjects: List[str],
    predicate: str,
    objects: List[str],
) -> str:
    """Deterministic claim ID from structured triple.

    Subject and object groups are internally sorted for dedup, but
    NEVER mixed with each other — (A→B) and (B→A) produce different IDs.

    DESIGN DECISION: Temporal scope (as_of_date) is deliberately EXCLUDED
    from this ID. `claim_id` represents the canonical thesis (e.g., "HBM is tight").
    Different time periods accumulate as evidence/history on the same claim,
    rather than splitting into separate claim IDs.
    """
    canonical = (
        tuple(sorted(s.upper().strip() for s in subjects)),
        predicate.upper().strip(),
        tuple(sorted(o.upper().strip() for o in objects)),
    )
    raw = repr(canonical)
    return hashlib.sha256(raw.encode()).hexdigest()[:16]


class Claim(BaseModel):
    """The atomic unit of the Graphite trust engine.

    Every assertion — "NVDA supplies GPUs to TSLA", "Cobalt supply is
    concentrated in DRC", "Project X's NPV depends on 92% recovery" —
    is a Claim backed by evidence, scored by confidence, and linked
    to other claims via dependency.

    Example:
        Claim(
            claim_text="NVIDIA supplies GPUs to Tesla",
            claim_type=ClaimType.RELATIONSHIP,
            subject_entities=["company:NVDA"],
            predicate="SUPPLIES_TO",
            object_entities=["company:TSLA"],
            assertion_mode=AssertionMode.EXTRACTED,
            origin=ClaimOrigin.EXTRACTOR,
            supporting_evidence=[...],
        )
    """
    # Identity — deterministic from (subjects, predicate, objects)
    claim_id: str = Field(default="", description="Auto-computed if empty. Hash of (subjects, predicate, objects)")
    claim_text: str = Field(description="Human-readable claim: 'NVDA supplies GPUs to TSLA'")
    claim_type: ClaimType
    granularity: ClaimGranularity = Field(
        default=ClaimGranularity.ATOMIC,
        description="Abstraction level: ATOMIC (extracted fact), SYNTHESIZED (combined), THESIS (high-level)",
    )

    # Structured triple
    subject_entities: List[str] = Field(description="NodeRef IDs: ['company:NVDA']")
    predicate: str = Field(description="Canonical relation: SUPPLIES_TO, DEPENDS_ON, EXPOSED_TO, etc.")
    object_entities: List[str] = Field(description="NodeRef IDs: ['company:TSLA']")

    # How this claim was asserted
    assertion_mode: AssertionMode = Field(default=AssertionMode.EXTRACTED)
    origin: ClaimOrigin = Field(default=ClaimOrigin.EXTRACTOR)

    # Agent provenance — tracks which agent/model generated this claim
    generator_id: str = Field(
        default="",
        description="Identifier of the generator: 'research-agent-v2', 'sec-extractor', etc.",
    )
    generation_metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Model version, prompt hash, temperature, and other generation context.",
    )

    # Temporal scope — when is this claim valid?
    as_of_date: str = Field(
        default="",
        description="Reference date for the claim, e.g. '2025-03-15' or 'FY2024'",
    )
    valid_from: str = Field(
        default="",
        description="Start of validity window, e.g. '2024-01-01'",
    )
    valid_to: str = Field(
        default="",
        description="End of validity window. Empty = still valid.",
    )

    # Evidence — the trust core
    supporting_evidence: List[Provenance] = Field(
        default_factory=list,
        description="Evidence quotes that back this claim",
    )
    weakening_evidence: List[Provenance] = Field(
        default_factory=list,
        description="Evidence quotes that undermine this claim",
    )

    # Confidence — explainable, computed
    confidence: Optional[ConfidenceResult] = Field(
        default=None,
        description="Computed confidence breakdown. None = not yet scored.",
    )

    # Status — machine verdict vs human override
    computed_status: ClaimStatus = Field(
        default=ClaimStatus.PENDING_REVIEW,
        description="Machine-derived status from evidence + confidence. "
        "Updated by compute_status().",
    )
    final_status: ClaimStatus = Field(
        default=ClaimStatus.PENDING_REVIEW,
        description="Authoritative status. Equals computed_status unless "
        "overridden by an analyst.",
    )
    override_reason: str = Field(
        default="",
        description="Why the analyst overrode the machine verdict. "
        "Empty if final_status == computed_status.",
    )

    # Claim-level dependency: "this claim depends on those claims"
    depends_on_claim_ids: List[str] = Field(
        default_factory=list,
        description="Claim IDs that this claim logically depends on. "
        "Used for claim-level blast radius: if a dependency weakens, "
        "this claim's confidence should be re-evaluated.",
    )

    # Review workflow
    review_state: ReviewState = Field(default=ReviewState.UNREVIEWED)
    reviewed_by: str = Field(default="", description="Reviewer identifier")
    reviewed_at: Optional[str] = Field(default=None)
    reviewer_note: Optional[str] = Field(default=None)

    # Audit
    extracted_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat(),
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Domain-specific metadata (domain, extractor version, etc.)",
    )

    def model_post_init(self, __context: Any) -> None:
        """Auto-compute claim_id if not provided."""
        if not self.claim_id:
            self.claim_id = _make_claim_id(
                self.subject_entities,
                self.predicate,
                self.object_entities,
            )

    def compute_status(
        self,
        support_threshold: float = 0.6,
        weak_threshold: float = 0.3,
    ) -> ClaimStatus:
        """Derive status from evidence and confidence.

        Updates computed_status. If no analyst override exists,
        also updates final_status to match.

        Returns:
            The computed ClaimStatus.
        """
        if not self.supporting_evidence:
            result = ClaimStatus.UNSUPPORTED
        elif self.supporting_evidence and self.weakening_evidence:
            result = ClaimStatus.MIXED
        elif self.confidence and self.confidence.score >= support_threshold:
            result = ClaimStatus.SUPPORTED
        elif self.confidence and self.confidence.score >= weak_threshold:
            result = ClaimStatus.WEAK
        elif self.confidence:
            result = ClaimStatus.UNSUPPORTED
        else:
            result = ClaimStatus.PENDING_REVIEW

        self.computed_status = result

        # Only update final_status if no analyst override
        if not self.is_overridden:
            self.final_status = result

        return result

    def override_status(
        self,
        status: ClaimStatus,
        reason: str,
        reviewer: str = "",
    ) -> None:
        """Analyst override of machine verdict.

        Sets final_status to the analyst's decision while preserving
        computed_status for auditability.
        """
        self.final_status = status
        self.override_reason = reason
        self.review_state = (
            ReviewState.APPROVED if status == ClaimStatus.SUPPORTED
            else ReviewState.REJECTED if status == ClaimStatus.UNSUPPORTED
            else ReviewState.NEEDS_FOLLOWUP
        )
        self.reviewed_by = reviewer
        self.reviewed_at = datetime.now(timezone.utc).isoformat()

    @property
    def is_reviewed(self) -> bool:
        return self.review_state != ReviewState.UNREVIEWED

    @property
    def is_overridden(self) -> bool:
        """True if an analyst explicitly set the status (Approved/Rejected/NeedsFollowup)."""
        return self.review_state in (
            ReviewState.APPROVED, ReviewState.REJECTED, ReviewState.NEEDS_FOLLOWUP
        )

    @property
    def evidence_count(self) -> int:
        return len(self.supporting_evidence) + len(self.weakening_evidence)


# ═══════════════════════════════════════
# LLM-Native Verification Report Models
# ═══════════════════════════════════════

class VerdictEnum(str, Enum):
    SUPPORTED = "SUPPORTED"
    CONFLICTED = "CONFLICTED"
    INSUFFICIENT = "INSUFFICIENT"


class ArgumentVerdictEnum(str, Enum):
    GROUNDED = "GROUNDED"
    CONCLUSION_JUMP = "CONCLUSION_JUMP"
    OVERSTATED = "OVERSTATED"


class VerdictRationale(BaseModel):
    """Structured reasoning slots for meta-evaluations and transparent auditing."""
    contradiction_type: Optional[str] = Field(default=None, description="e.g., numeric mismatch, entity mismatch")
    missing_evidence_reason: Optional[str] = Field(default=None, description="Why the evidence was insufficient or lacking")
    temporal_alignment: Optional[str] = Field(default=None, description="e.g., stale evidence vs current claim timeline")
    text: str = Field(description="Free-form rationale from the LLM judge")


class Verdict(BaseModel):
    """A claim-level judgment returned by the verifier pipeline."""
    claim_id: str
    claim_text: str
    verdict: VerdictEnum
    supporting_evidence_ids: List[str] = Field(default_factory=list)
    conflicting_evidence_ids: List[str] = Field(default_factory=list)
    rationale: VerdictRationale
    needs_human_review: bool = Field(default=False, description="Flag for high-risk or low-confidence verdicts to route to human queues")
    cited_span: Optional[str] = Field(default=None, description="The exact span from the evidence corpus cited to make the verdict")
    model_version: str = Field(default="")
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


class ArgumentVerdict(BaseModel):
    """An argument-level verification representing semantic logic jumps."""
    text: str = Field(description="The argument chain or conclusion being evaluated")
    verdict: ArgumentVerdictEnum
    rationale: VerdictRationale
    needs_human_review: bool = Field(default=False)


class VerificationReport(BaseModel):
    """Top-level review object aggregating the entire verification workflow."""
    document_id: str
    total_claims: int = 0
    supported_count: int = 0
    conflicted_count: int = 0
    insufficient_count: int = 0
    grounded_argument_count: int = 0
    conclusion_jump_count: int = 0
    risky_claim_ids: List[str] = Field(default_factory=list, description="Claim IDs flagged for human review")
    evidence_coverage_score: float = 0.0
    verdicts: List[Verdict] = Field(default_factory=list)
    argument_verdicts: List[ArgumentVerdict] = Field(default_factory=list)
    model_metadata: Dict[str, Any] = Field(default_factory=dict)

    def get_verdict(self, claim_id: str) -> Optional[Verdict]:
        for v in self.verdicts:
            if v.claim_id == claim_id:
                return v
        return None
